# site info
title: lillemets.ee
description: > # this means to ignore newlines until "baseurl:"
  Jüri Lillemets
timezone: Europe/Tallinn 
url: www.lillemets.ee 
baseurl: ""

# author info
email: jyri.lillemets@emu.ee
github_username: lillemets
disqus_shortname: 'lillemets'

# build settings
markdown: kramdown
highlighter: pygments
destination: /home/jrl/drop/Dropbox/Apps/Pancake.io/lillemets
permalink: none

# addons
gems:
    - jekyll-paginate
paginate: 10
paginate_path: "/blog/page:num/"

# menu
collections:
  projects:
    output: true
    permalink: :title.html
  texts:
    output: true
    permalink: :title.html

# defaults
defaults:
  -
    scope:
      type:         "projects"
    values:
      layout:       "post"
  -
    scope:
      type:         "texts"
    values:
      layout:       "post"
  -
    scope:
      type:         "posts"
    values:
      layout:       "post"
