# site info
title: lillemets.ee
description: > # this means to ignore newlines until "baseurl:"
  Jüri Lillemets
timezone: Europe/Tallinn 
url: www.lillemets.ee 
baseurl: ""

# author info
email: jyri.lillemets@emu.ee
twitter_username: twitter_username
github_username:  github_username

# build settings
markdown: kramdown
highlighter: pygments
destination: /home/jrl/drop/Dropbox/Apps/Pancake.io/lillemets
permalink: none

# gems
gems:
    - jekyll-paginate
paginate: 10
paginate_path: "/blog/page:num/"

# menu
collections:
  portfolio:
    output: true
    permalink: /portfolio/:path.html
  poetry:
    output: true
    permalink: /poetry/:path.html


