# site info
title: lillemets.ee
description: > # this means to ignore newlines until "baseurl:"
  Jüri Lillemets
timezone: Europe/Tallinn 
url: lillemets.github.io/oldsite

# author info
email: jyri.lillemets@emu.ee
github_username: lillemets
disqus_shortname: 'lillemets'

# build settings
markdown: kramdown
highlighter: rouge
destination: 
permalink: none

# addons
plugins:
    - jekyll-paginate
paginate: 10
paginate_path: "/blog/page:num/"

# menu
collections:
  texts:
    output: true
    permalink: :title.html

# defaults
defaults:
  -
    scope:
      type:         "texts"
    values:
      layout:       "post"
  -
    scope:
      type:         "posts"
    values:
      layout:       "post"
